### ISSUE TITLE
[discussion] Add support for config loader providers in addition to functions

### ISSUE THREAD

**Issue by vlad-ostrovski** [nestjs/config#893]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently the `load` property in `ConfigModuleOptions` only accepts config loader functions. When building the returned object, it is impossible to use anything that is already in the nest DI container which is a shame. It also makes those functions less testable.

### Describe the solution you'd like

Add support for passing `Provider`s into the `load` property (a provider is built behind the scenes for every loader function anyways). This way, a user can supply the config object in a more 'nestjs' way, use the existing DI container inside the provider and make the whole process more testable.

### What is the motivation / use case for changing the behavior?

Use DI inside loader functions
Easier to test
Nestjs users generally think more in a provider way than in a loader function way. A provider fits the entire framework better.

**Comment by vlad-ostrovski** [comment]
Yes of course.

I'm bringing in some environment variable overrides from a remote location (aws ssm). What I ultimately need to do is to look at the current `process.env` (after environment variable and local `.env` loading) and decide what to override in process.env based on the already present values.

I have two options:

1. Bring in the remote values, construct a `.env.remote` (or potentially more than one) file, and pass both `.env` and `.env.remote` as file paths to the config service  in an order that will enforce my override logic.
2. Create a special config loader that will always be the first in the config loader chain, the internal logic of this loader can look at the current state of the `process.env` (which is after loading the local `.env`) and modify the `process.env` inside the loader based on my logic. This way all loaders that comes after this loader, receive a correct state of `process.env`.

The second option sounds better to me. But the problem is all my aws code is written in a DI way, like we like it in nestjs :) and so, in order to use aws inside the loader function, I need to create aws-clients outside of my proper and testable aws code. 
This also make the special loader function logic less testable because I can't inject mocked aws parts.

Now when I think about it, It would also be great to be able to inject the `ConfigService` itself inside this type of config provider (the feature requested), this way a loader can see the current state of the whole configuration and make decisions about it's own provided configuration (to make a sort of loader-reduce operation). Loaders do not modify the `process.env`, so there is no way inside a loader function to know what configuration has already been loaded by a previous loader function. This will also make testing those loaders great because relying on `process.env` in jest tests is kinda awkward and relying on the `ConfigService` instead is very convenient.

**Comment by benkroeger** [comment]
[custom validate functions](https://docs.nestjs.com/techniques/configuration#custom-validate-function) are actually executed between .env files + env vars and loaders invocation.

see [code here](https://github.com/nestjs/config/blob/master/lib/config.module.ts#L63)

**Comment by regevbr** [comment]
> [custom validate functions](https://docs.nestjs.com/techniques/configuration#custom-validate-function) are actually executed between .env files + env vars and loaders invocation.
> 
> see [code here](https://github.com/nestjs/config/blob/master/lib/config.module.ts#L63)

Thanks but I don't think help as it is not async and there is no access to the DI in those functions, nor they are testable. Thoughts?

**Comment by benkroeger** [comment]
pretty unusual requests for a config module.
It's true that you can't use DI for the validate function - it's purpose is to validate environment variables (which are available in sync access).
What sort of aws checks do you have to do that are not possible by checking env vars?
Also, modifying process.env doesn't seem like a good idea.
Loaders are not executed in order. they are transformed into FactoryProviders and injected through DI.

However, what you can do is to create a custom config module that implements a `forRootAsync` method, resolve whatever you need in there then import `@nestjs/config` in there. Obviously re-export it as well.

**Comment by benkroeger** [comment]
[this](https://github.com/nestjs/config/blob/1a8c718025198db6013bcf349074dc94dfc0996a/lib/utils/create-config-factory.util.ts#L7) is how your `loader` functions are converted into providers.
So a low-hanging fruit would be to check for `inject` props on the loader function.
Not sure about the resolution scope though. Since these providers are resolved inside the ConfigModule, any injected dependency would have to be available in that module as well.

**Comment by jmcdo29** [comment]
What about creating your own `ConfigService` that uses Nest's base `COnfigService` but also uses an `onModuleInit()` to pull data down from AWS and has getters for your env values? You could validate once you get data back from AWS, thje only thing you'd be missing is the `namespace` feature

**Comment by regevbr** [comment]
Hi guys, thanks for the productive conversation :-)

I still feel as there is no other way to address our needs, other than adding direct support to the library.
I have taken the liberty of creating a [PR](#894) that addresses our needs. I hope that by looking at the PR, the added tests, and the description, you can gain a better understanding of what we are trying to achieve. Hopefully, eventually, we will be able to merge it, or find another solution :-)

**Comment by jmcdo29** [comment]
Even with looking at the PR's test, I'm still not sure why this couldn't be managed by a class that injects or extends the `ConfigService`, gets the information from AWS, and then does validation on it and exposes its own methods for providing those values. I don't see why the `ConfigService` needs its loaders to be async-able rather than using a feature of Nest in the first place

**Comment by kamilmysliwiec** [comment]
I agree with @jmcdo29. Adding more features into existing libraries (that aren't blocking and do not cover cases that are not doable/can't be currently accomplished with the framework) is a double-edged sword as it makes them harder to learn, maintain, and also require adding more docs = devs time to learn them.
